const canvas=document.getElementById('game');
const ctx=canvas.getContext('2d');
const root=document.getElementById('ui');
const TAU=Math.PI*2;
const SAVE='forge-drifterling-v2';
let W=innerWidth,H=innerHeight,DPR=Math.min(devicePixelRatio||1,2),started=false,paused=true,settings=false,muted=false,last=performance.now(),time=0;
const keys=new Set();
const touchKeys=new Set();
const player={x:0,y:0,vx:0,vy:0,r:18,trail:[]};
const colors={cyan:'#7ec8d4',gold:'#e8c07a',violet:'#b08ad6',prism:'#ead2ea'};
const islands=[
{id:'meadow',name:'Mist Meadow',x:-420,y:-120,r:105,need:'cyan',color:'#7ec8d4'},
{id:'sunstone',name:'Sunstone Reach',x:380,y:-300,r:115,need:'gold',color:'#e8c07a'},
{id:'grove',name:'Violet Grove',x:620,y:260,r:120,need:'violet',color:'#b08ad6'},
{id:'falls',name:'Prism Falls',x:-220,y:470,r:118,need:'prism',color:'#ead2ea'},
{id:'heart',name:'Heart Isle',x:80,y:80,r:145,need:'heart',color:'#e8e6e1'}
];
let inventory=[];let restored=new Set();let cam={x:0,y:0};let hint='';let hintUntil=0;let particles=[];let orbs=[];let audioCtx=null;
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,2);canvas.width=W*DPR;canvas.height=H*DPR;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0)}
addEventListener('resize',resize);resize();
function save(){try{localStorage.setItem(SAVE,JSON.stringify({x:player.x,y:player.y,restored:[...restored],inventory,muted}))}catch{}}
function load(){try{const s=JSON.parse(localStorage.getItem(SAVE)||'null');if(s){player.x=s.x||0;player.y=s.y||0;restored=new Set(s.restored||[]);inventory=s.inventory||[];muted=!!s.muted;return true}}catch{}return false}
function clearSave(){try{localStorage.removeItem(SAVE)}catch{}}
function rnd(a,b){return a+Math.random()*(b-a)}
function dist(a,b,c,d){return Math.hypot(c-a,d-b)}
function initOrbs(){orbs=[];const defs=[['cyan',-650,-360],['cyan',-520,120],['cyan',-290,-410],['gold',520,-520],['gold',650,-100],['gold',280,-560],['violet',780,90],['violet',500,520],['violet',850,390],['prism',-520,520],['prism',-80,680],['prism',-650,260]];defs.forEach(([kind,x,y],i)=>orbs.push({kind,x:x+rnd(-35,35),y:y+rnd(-35,35),taken:false,phase:i}))}
initOrbs();
function tone(f=440,d=.12){if(muted)return;try{audioCtx??=new (AudioContext||webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.06,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch{}}
function burst(x,y,c,n=16){for(let i=0;i<n;i++){const a=Math.random()*TAU,s=rnd(25,95);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rnd(.5,1.2),max:1.2,c})}}
function showHint(t,sec=2.5){hint=t;hintUntil=time+sec;renderUI()}
function axis(){let x=0,y=0;const all=new Set([...keys,...touchKeys]);if(all.has('ArrowLeft')||all.has('KeyA'))x--;if(all.has('ArrowRight')||all.has('KeyD'))x++;if(all.has('ArrowUp')||all.has('KeyW'))y--;if(all.has('ArrowDown')||all.has('KeyS'))y++;const m=Math.hypot(x,y)||1;return{x:x/m,y:y/m}}
function canRestore(i){if(i.id==='heart')return ['meadow','sunstone','grove','falls'].every(id=>restored.has(id));return inventory.includes(i.need)}
function restore(i){if(restored.has(i.id)||!canRestore(i))return;if(i.id!=='heart')inventory.splice(inventory.indexOf(i.need),1);restored.add(i.id);burst(i.x,i.y,i.color,42);tone(i.id==='heart'?523:330,.6);showHint(i.id==='heart'?'THE SKY REMEMBERS.':i.name.toUpperCase(),3);save();renderUI()}
function update(dt){if(!started||paused||settings)return;time+=dt;const a=axis(),boost=keys.has('Space');const speed=boost?250:195;const responsiveness=1-Math.exp(-6*dt);player.vx+=(a.x*speed-player.vx)*responsiveness;player.vy+=(a.y*speed-player.vy)*responsiveness;if(a.x===0&&a.y===0){player.vx*=Math.exp(-2.5*dt);player.vy*=Math.exp(-2.5*dt)}player.x+=player.vx*dt;player.y+=player.vy*dt;
player.trail.push({x:player.x,y:player.y,t:time});while(player.trail.length>40)player.trail.shift();
for(const o of orbs){if(o.taken)continue;if(dist(player.x,player.y,o.x,o.y)<32){o.taken=true;if(inventory.length>=3)inventory.shift();inventory.push(o.kind);burst(o.x,o.y,colors[o.kind]);tone({cyan:620,gold:540,violet:700,prism:820}[o.kind]);showHint('COLOR FOUND',1.2);save();renderUI()}}
for(const i of islands){if(!restored.has(i.id)&&dist(player.x,player.y,i.x,i.y)<i.r*.58&&canRestore(i))restore(i)}
for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.exp(-2*dt);p.vy*=Math.exp(-2*dt);p.life-=dt}particles=particles.filter(p=>p.life>0);cam.x+=(player.x-cam.x)*(1-Math.exp(-2.2*dt));cam.y+=(player.y-cam.y)*(1-Math.exp(-2.2*dt));}
function sx(x){return x-cam.x+W/2}function sy(y){return y-cam.y+H/2}
function glow(x,y,r,c,a=.3){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,c);g.addColorStop(1,'transparent');ctx.globalAlpha=a;ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill();ctx.globalAlpha=1}
function draw(){ctx.clearRect(0,0,W,H);const bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#0b1020');bg.addColorStop(1,'#10192b');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);
for(let i=0;i<80;i++){const x=((i*137.5+time*3)% (W+160))-80,y=((i*73.2)% (H+120))-60;ctx.fillStyle='rgba(190,210,230,.12)';ctx.fillRect(x,y,1,1)}
for(const i of islands){const x=sx(i.x),y=sy(i.y),on=restored.has(i.id);glow(x,y,i.r*1.6,i.color,on?.28:.08);ctx.fillStyle=on?i.color:'#232b42';ctx.globalAlpha=on?.65:.45;ctx.beginPath();ctx.ellipse(x,y,i.r,i.r*.55,0,0,TAU);ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=on?'rgba(255,255,255,.35)':'rgba(255,255,255,.10)';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='rgba(232,230,225,.65)';ctx.font='500 12px system-ui';ctx.textAlign='center';ctx.fillText(i.name,x,y+i.r*.42+18);if(!on&&canRestore(i)){ctx.fillStyle='rgba(232,230,225,.75)';ctx.fillText('ENTER TO RESTORE',x,y-i.r*.4)}}
for(const o of orbs){if(o.taken)continue;const x=sx(o.x),y=sy(o.y),r=6+Math.sin(time*3+o.phase)*1.5;glow(x,y,22,colors[o.kind],.35);ctx.fillStyle=colors[o.kind];ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill()}
for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(sx(p.x),sy(p.y),2.2,0,TAU);ctx.fill()}ctx.globalAlpha=1;
for(let i=1;i<player.trail.length;i++){const a=player.trail[i-1],b=player.trail[i],t=i/player.trail.length;ctx.strokeStyle=`rgba(180,220,230,${t*.16})`;ctx.lineWidth=1+t*3;ctx.beginPath();ctx.moveTo(sx(a.x),sy(a.y));ctx.lineTo(sx(b.x),sy(b.y));ctx.stroke()}
const px=sx(player.x),py=sy(player.y);glow(px,py,42,'#d9dde6',.32);ctx.save();ctx.translate(px,py);const ang=Math.atan2(player.vy,player.vx);ctx.rotate(Number.isFinite(ang)?ang:0);ctx.fillStyle='#d9dde6';ctx.beginPath();ctx.ellipse(0,0,20,15,0,0,TAU);ctx.fill();ctx.fillStyle='#0b1020';ctx.beginPath();ctx.arc(7,-4,2,0,TAU);ctx.fill();ctx.strokeStyle='rgba(217,221,230,.45)';ctx.lineWidth=2;for(let j=-2;j<=2;j++){ctx.beginPath();ctx.moveTo(-14,j*4);ctx.quadraticCurveTo(-30-rnd(0,5),j*5+Math.sin(time*3+j)*4,-42,j*7);ctx.stroke()}ctx.restore();
if(!started){ctx.fillStyle='rgba(11,16,32,.35)';ctx.fillRect(0,0,W,H)}}
function renderUI(){if(!started){const has=!!localStorage.getItem(SAVE);root.innerHTML=`<div class="screen"><div class="title-wrap"><div class="eyebrow">Return the color</div><h1>Drifterling</h1><p class="subtitle">A small creature, an enormous sky. Glide, gather lost color, and wake the sleeping islands.</p><button class="primary" data-a="start">${has?'Continue':'Begin'}</button><p class="micro">Touch: four-way pad. Keyboard: arrows or WASD.</p></div></div>`}else{let h=`<div class="hud"><div class="top"><div class="progress">${islands.map(i=>`<span class="dot ${restored.has(i.id)?'on':''}"></span>`).join('')}</div><div class="actions"><button class="icon" data-a="mute">${muted?'🔇':'🔊'}</button><button class="icon" data-a="pause">${paused?'▶':'Ⅱ'}</button><button class="icon" data-a="settings">⚙</button></div></div>`;if(hint&&time<hintUntil)h+=`<div class="hint">${hint}</div>`;if(matchMedia('(pointer:coarse)').matches&&!paused&&!settings)h+=`<div class="dpad" data-ui><span></span><button data-d="ArrowUp">↑</button><span></span><button data-d="ArrowLeft">←</button><span class="core"></span><button data-d="ArrowRight">→</button><span></span><button data-d="ArrowDown">↓</button><span></span></div>`;if(paused&&!settings)h+=`<div class="overlay"><div class="panel"><h2>Paused</h2><div class="row"><button data-a="resume">Resume</button></div></div></div>`;if(settings)h+=`<div class="overlay"><div class="panel"><h2>Settings</h2><p>Touch uses only the four-way pad. Keyboard uses WASD or arrows.</p><div class="row"><button data-a="mute" class="secondary">${muted?'Sound off':'Sound on'}</button><button data-a="close" class="secondary">Close</button><button data-a="reset" class="ghost">Reset journey</button></div></div></div>`;root.innerHTML=h+'</div>'}bindUI()}
function bindUI(){root.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{const a=b.dataset.a;if(a==='start'){const had=load();if(!had){player.x=0;player.y=0}started=true;paused=false;showHint(matchMedia('(pointer:coarse)').matches?'USE THE ARROWS':'DRAG OR USE ARROWS',4);tone(440,.2)}if(a==='mute'){muted=!muted;save();renderUI()}if(a==='pause'){paused=!paused;renderUI()}if(a==='resume'){paused=false;renderUI()}if(a==='settings'){settings=true;paused=true;renderUI()}if(a==='close'){settings=false;paused=false;renderUI()}if(a==='reset'){clearSave();player.x=player.y=player.vx=player.vy=0;inventory=[];restored=new Set();initOrbs();settings=false;paused=false;save();renderUI()}});root.querySelectorAll('[data-d]').forEach(b=>{const k=b.dataset.d;const dn=e=>{e.preventDefault();touchKeys.add(k);try{b.setPointerCapture(e.pointerId)}catch{}};const up=e=>{e?.preventDefault?.();touchKeys.delete(k)};b.onpointerdown=dn;b.onpointerup=up;b.onpointercancel=up;b.onlostpointercapture=up;b.oncontextmenu=e=>e.preventDefault()})}
addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space','KeyW','KeyA','KeyS','KeyD','Escape','KeyP'].includes(e.code))e.preventDefault();keys.add(e.code);if((e.code==='Escape'||e.code==='KeyP')&&started){paused=!paused;renderUI()}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();touchKeys.clear()});
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(frame)}
renderUI();requestAnimationFrame(frame);