const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const origin = process.env.ARCADE_TEST_URL || 'http://127.0.0.1:8420';
const artifacts = process.env.ARCADE_ARTIFACTS || '/workspace/moonlit-artifacts';
const key = 'forge-arcade-moonlit-terrarium-v1';
(async () => {
  fs.mkdirSync(artifacts, { recursive: true });
  const browser = await chromium.launch({ executablePath: '/usr/bin/chromium', args: ['--no-sandbox'] });
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 }, hasTouch: true });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(origin);
  await page.locator('#grid [data-game="moonlit-terrarium"]').click();
  await page.waitForFunction(() => document.getElementById('pauseBtn')?.disabled === true);
  await page.locator('#startBtn').focus(); await page.keyboard.press('Enter');
  await page.locator('#btnFood').focus(); await page.keyboard.press('Enter');
  await page.keyboard.press('ArrowLeft'); await page.keyboard.press('Enter');
  assert(await page.locator('#btnFood').isDisabled());
  let saved = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), key);
  assert.equal(saved.interventions.length, 1); assert.equal(saved.interventions[0].x, 460);
  await page.locator('[data-mote="0"]').click();
  assert((await page.locator('#moteInfo').innerText()).includes('Curious'));
  await page.locator('#pauseBtn').click();
  const time = await page.locator('#timeValue').innerText();
  await page.waitForTimeout(250); assert.equal(await page.locator('#timeValue').innerText(), time);
  await page.locator('#soundBtn').click();
  await page.locator('#motionBtn').click();
  await page.screenshot({ path: `${artifacts}/desktop.png`, fullPage: true });
  await page.locator('#forge-back-link').click();
  await page.locator('#grid [data-game="moonlit-terrarium"]').click();
  await page.locator('#continueBtn').click();
  assert.equal(await page.locator('#pauseBtn').innerText(), 'Resume');
  assert.equal(await page.locator('#timeValue').innerText(), time);
  assert.equal(await page.locator('#soundBtn').innerText(), 'Sound: On');
  page.once('dialog', dialog => dialog.dismiss()); await page.locator('#restartBtn').click();
  assert(await page.locator('#startOverlay').isHidden());
  await page.locator('#pauseBtn').click();
  assert.equal(await page.locator('#pauseBtn').innerText(), 'Pause');
  // Seed only the night clock to test dawn through the real frame loop.
  await page.goto(origin);
  await page.evaluate(key => { const data = JSON.parse(localStorage.getItem(key)); data.manualPause = false; data.timeLeft = 0.2; localStorage.setItem(key, JSON.stringify(data)); }, key);
  await page.goto(`${origin}/games/moonlit-terrarium/index.html`); await page.locator('#continueBtn').click();
  await page.waitForFunction(() => document.getElementById('nightValue').textContent === '2 / 7');
  assert((await page.locator('#nightSummary').innerText()).includes('Night 1:'));
  assert(!(await page.locator('#btnWater').isDisabled()));
  // The final dawn is durable and can be reopened as a completed story.
  await page.locator('#pauseBtn').click();
  await page.goto(origin);
  await page.evaluate(key => { const data = JSON.parse(localStorage.getItem(key)); data.manualPause = false; data.night = 7; data.timeLeft = 0.2; localStorage.setItem(key, JSON.stringify(data)); }, key);
  await page.goto(`${origin}/games/moonlit-terrarium/index.html`); await page.locator('#continueBtn').click();
  await page.waitForSelector('#victoryOverlay:not(.hidden)');
  await page.goto(`${origin}/games/moonlit-terrarium/index.html`); await page.locator('#continueBtn').click();
  assert(await page.locator('#victoryOverlay').isVisible());
  assert((await page.locator('#victoryText').innerText()).includes('completed story'));
  for (const viewport of [{ width: 320, height: 568 }, { width: 390, height: 844 }, { width: 844, height: 390 }]) {
    await page.setViewportSize(viewport);
    await page.goto(origin);
    await page.evaluate(() => localStorage.clear()); await page.goto(`${origin}/games/moonlit-terrarium/index.html`);
    await page.locator('#startBtn').click();
    await page.locator('#btnShelter').click();
    const rect = await page.locator('#terrarium').boundingBox();
    await page.locator('#terrarium').tap({ position: { x: rect.width / 2, y: rect.height / 2 } });
    assert(await page.locator('#btnShelter').isDisabled());
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.locator('[data-mote="1"]').click();
    assert((await page.locator('#moteInfo').innerText()).includes('Pip'));
    await page.screenshot({ path: `${artifacts}/${viewport.width}x${viewport.height}.png`, fullPage: true });
  }
  await page.goto(origin);
  await page.evaluate(key => localStorage.setItem(key, '{broken'), key); await page.goto(`${origin}/games/moonlit-terrarium/index.html`);
  assert(await page.locator('#continueBtn').isHidden());
  assert.deepEqual(errors, []);
  await browser.close(); console.log('Desktop/mobile game playtests passed; screenshots:', artifacts);
})().catch(error => { console.error(error); process.exit(1); });
