const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const url = process.env.ARCADE_TEST_URL || 'http://127.0.0.1:8420';
const artifacts = process.env.ARCADE_ARTIFACTS || '/workspace/integration-artifacts';

(async () => {
  fs.mkdirSync(artifacts, { recursive: true });
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/usr/bin/chromium', args: ['--no-sandbox'] });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [], missing = [];
  page.on('pageerror', e => errors.push({ url: page.url(), message: e.message }));
  page.on('response', response => { if (response.url().startsWith(url) && response.status() >= 400) missing.push(response.url()); });
  await page.goto(url, { waitUntil: 'networkidle' });
  const registry = await page.evaluate(() => GAMES.map(g => ({ id: g.id, category: g.category, featured: !!g.featured })));
  assert.equal(registry.filter(g => g.id === 'outpost-orbit').length, 1);
  const game = registry.find(g => g.id === 'outpost-orbit');
  assert.equal(game.category, 'Simulations');
  assert.equal(game.featured, true);
  const shortcut = await page.locator('.arcanum-shortcut').getAttribute('href');
  const card = page.locator('#grid [data-game="outpost-orbit"]');
  assert.equal(await card.locator('h3').innerText(), 'Outpost Orbit');
  assert((await card.locator('.card-desc').innerText()).includes('Guide a tiny autonomous alien colony'));
  assert.equal(await card.getAttribute('href'), 'games/outpost-orbit/index.html');
  assert((await card.locator('.card-art').evaluate(e => getComputedStyle(e, '::after').backgroundImage)).includes('data:image/svg+xml'));
  await card.scrollIntoViewIfNeeded();
  await card.screenshot({ path: `${artifacts}/desktop-card.png` });
  assert.equal(await page.locator('#featured-grid [data-game="outpost-orbit"]').count(), 1);
  for (const category of ['Simulations', 'Featured', 'Games', 'Experiments', 'All']) {
    await page.locator(`[data-cat="${category}"]`).click();
    assert.equal(await page.locator('#grid [data-game="outpost-orbit"]').count(), ['Games', 'Experiments'].includes(category) ? 0 : 1);
  }
  await card.click();
  await page.waitForURL('**/games/outpost-orbit/index.html');
  await page.waitForFunction(() => window.outpost?.state?.aliens.length === 5);
  await page.locator('[data-speed="0"]').click();
  const originTime = await page.evaluate(() => outpost.state.time);
  await page.waitForTimeout(500);
  assert.equal(await page.evaluate(() => outpost.state.time), originTime);
  await page.locator('[data-panel="build"]').click();
  await page.locator('[data-build="habitat"]').click();
  let pos = await page.evaluate(() => outpost.screen(-130, 0));
  await page.mouse.click(pos.x, pos.y);
  await page.locator('[data-panel="build"]').click();
  await page.locator('[data-build="garden"]').click();
  pos = await page.evaluate(() => outpost.screen(-45, -105));
  await page.mouse.click(pos.x, pos.y);
  assert.equal(await page.evaluate(() => outpost.state.buildings.length), 4);
  await page.locator('[data-panel="priorities"]').click();
  await page.locator('[data-priority="build"][data-value="2"]').click();
  await page.locator('[data-priority="food"][data-value="2"]').click();
  await page.locator('#close-panel').click();
  for (const speed of [1, 2, 4, 8]) {
    await page.locator(`[data-speed="${speed}"]`).click();
    assert.equal(await page.evaluate(() => outpost.state.speed), speed);
  }
  await page.waitForFunction(() => outpost.state.buildings.every(b => b.progress === 1), { timeout: 45000 });
  await page.waitForFunction(() => outpost.state.discoveries.some(d => d.found) && outpost.state.log.some(e => e.kind === 'MOON STORIES'), { timeout: 45000 });
  const moved = await page.evaluate(() => outpost.state.aliens.some(a => Math.abs(a.x) > 100 || Math.abs(a.y) > 100));
  assert(moved);
  await page.locator('[data-panel="villagers"]').click();
  for (const [id, trait] of [[0, 'CURIOUS'], [1, 'SOCIAL'], [3, 'LAZY']]) {
    await page.locator(`[data-alien="${id}"]`).click();
    assert((await page.locator('#panel').innerText()).includes(trait));
    await page.locator('#close-panel').click();
    if (id !== 3) await page.locator('[data-panel="villagers"]').click();
  }
  await page.locator('#home').click();
  await page.locator('#cinematic').click();
  assert(await page.locator('body').evaluate(e => e.classList.contains('cinematic')));
  assert(await page.locator('.time-controls').isVisible());
  assert(await page.locator('#forge-back-link').isVisible());
  await page.locator('#cinematic').click();
  await page.locator('[data-speed="0"]').click();
  const saved = await page.evaluate(() => { outpost.save(); localStorage.setItem('integration-unrelated-game', 'keep'); return JSON.stringify(outpost.state); });
  await page.reload({ waitUntil: 'networkidle' });
  assert.equal(await page.evaluate(() => JSON.stringify(outpost.state)), saved);
  assert.equal(await page.evaluate(() => localStorage.getItem('integration-unrelated-game')), 'keep');
  await page.screenshot({ path: `${artifacts}/integrated-village.png` });
  await page.locator('#forge-back-link').click();
  await page.waitForURL('**/index.html');
  assert.equal(await page.locator('.arcanum-shortcut').getAttribute('href'), shortcut);
  for (const [id, category] of [['moonlit-terrarium', 'Simulations'], ['signal-garden', 'Experiments'], ['night-run-forge', 'Games']]) {
    await page.locator(`[data-cat="${category}"]`).click();
    await page.locator(`#grid [data-game="${id}"]`).click();
    await page.waitForURL(`**/games/${id}/index.html`);
    await page.waitForTimeout(900);
    assert(await page.locator('canvas').count() > 0);
    const back = page.locator('a[href="../../index.html"]').first();
    await page.screenshot({ path: `${artifacts}/existing-${id}.png` });
    if (await back.count()) await back.click();
    else await page.goBack();
    await page.waitForURL('**/index.html');
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('[data-cat="Simulations"]').click();
  await card.scrollIntoViewIfNeeded();
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await card.screenshot({ path: `${artifacts}/mobile-card.png` });
  await card.click();
  await page.waitForURL('**/games/outpost-orbit/index.html');
  await page.locator('#home').click();
  const boxes = await page.locator('footer, #forge-back-link').evaluateAll(nodes => nodes.map(e => { const b = e.getBoundingClientRect(); return { y: b.y, bottom: b.bottom }; }));
  assert(boxes[0].bottom <= boxes[1].y);
  await page.locator('[data-panel="villagers"]').click();
  await page.locator('[data-alien="2"]').click();
  let bounds = await page.locator('#panel').boundingBox();
  assert(bounds.x >= 0 && bounds.x + bounds.width <= 390 && bounds.y >= 0);
  await page.screenshot({ path: `${artifacts}/mobile-panel.png` });
  await page.locator('#close-panel').click();
  const before = await page.evaluate(() => ({ ...outpost.camera }));
  const cdp = await page.context().newCDPSession(page);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 170, y: 350, id: 1 }] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 230, y: 380, id: 1 }] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  assert.notEqual(await page.evaluate(() => outpost.camera.x), before.x);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 140, y: 340, id: 1 }, { x: 230, y: 340, id: 2 }] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 110, y: 340, id: 1 }, { x: 260, y: 340, id: 2 }] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  assert(await page.evaluate(() => outpost.camera.zoom) > before.zoom);
  await page.locator('#home').click();
  await page.setViewportSize({ width: 844, height: 390 });
  await page.locator('[data-panel="build"]').click();
  bounds = await page.locator('#panel').boundingBox();
  assert(bounds.y >= 0 && bounds.y + bounds.height <= 390);
  const landscapeBoxes = await page.locator('footer, #forge-back-link').evaluateAll(nodes => nodes.map(e => { const b = e.getBoundingClientRect(); return { y: b.y, bottom: b.bottom }; }));
  assert(landscapeBoxes[0].bottom <= landscapeBoxes[1].y);
  await page.screenshot({ path: `${artifacts}/landscape-panel.png` });
  await page.locator('#close-panel').click();
  await page.locator('#forge-back-link').click();
  await page.waitForURL('**/index.html');
  assert(await page.locator('#grid [data-game="outpost-orbit"]').count() === 1);
  assert.deepEqual(missing, []);
  assert.deepEqual(errors, []);
  fs.writeFileSync(`${artifacts}/browser-result.json`, JSON.stringify({ passed: true, gameCount: registry.length, existingGamesTested: ['moonlit-terrarium', 'signal-garden', 'night-run-forge'], missing, errors }, null, 2));
  console.log('PASS: library, featured/category filters, coded art, native launch/return, construction, priorities, needs/personalities, all speeds, exploration/events, cinematic, save/reload, three existing games, mobile pan/pinch/portrait/landscape, no local 404s or runtime errors.');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
