function updateAllUI(){
  $('hudCredits').textContent=fmt(save.credits);$('hudBest').textContent=fmt(save.bestAlt)+' KM';$('menuCredits').textContent=fmt(save.credits);$('menuBest').textContent=fmt(save.bestAlt)+' KM';$('lifetimeText').textContent=fmt(save.lifetimeAlt)+' KM lifetime • '+fmt(save.flights)+' flights';
  const ri=rankInfo();$('rankText').textContent=ri.cur.name;if(ri.max){$('nextRankName').textContent='MAX RANK';$('rankProgressText').textContent='COMPLETE';$('rankProgress').style.width='100%'}else{const span=ri.next.xp-ri.cur.xp,p=clamp((save.xp-ri.cur.xp)/span,0,1);$('nextRankName').textContent=ri.next.name;$('rankProgressText').textContent=fmt(save.xp-ri.cur.xp)+' / '+fmt(span)+' XP';$('rankProgress').style.width=(p*100).toFixed(1)+'%'}
  const m=nextMilestone();if(m){$('milestoneName').textContent='Reach '+fmt(m.alt)+' KM • '+m.label;$('milestoneReward').textContent='+'+fmt(m.reward);$('milestoneProgress').style.width=(clamp(save.bestAlt/m.alt,0,1)*100).toFixed(1)+'%'}else{$('milestoneName').textContent='ALL MILESTONES CLEARED';$('milestoneReward').textContent='LEGEND';$('milestoneProgress').style.width='100%'}
  ['engine','fuel','stages'].forEach(type=>{const btn=$(type+'Buy'),lvl=$(type+'Level'),c=cost(type);lvl.textContent='LVL '+save[type]+' / '+MAX[type];if(c===Infinity){btn.textContent='MAX';btn.disabled=true;btn.classList.add('max')}else{btn.textContent=fmt(c);btn.disabled=save.credits<c;btn.classList.remove('max')}});
  updateDailyUI();
  updateCosmeticsUI();
  $('audioBtn').textContent=save.isMuted?'×':'♪';
}
function buy(type){if(state!==STATE.MENU)return;const c=cost(type);if(!Number.isFinite(c)||save.credits<c)return;save.credits-=c;save[type]++;persist();updateAllUI();audio.tone(690,'triangle',.12,.15);toast(type==='engine'?'BOOSTER UPGRADED':type==='fuel'?'FUEL CELL UPGRADED':'STACK FRAME UPGRADED','cyan')}
$('engineBuy').onclick=e=>{e.stopPropagation();buy('engine')};$('fuelBuy').onclick=e=>{e.stopPropagation();buy('fuel')};$('stagesBuy').onclick=e=>{e.stopPropagation();buy('stages')};
$('audioBtn').onclick=e=>{e.stopPropagation();save.isMuted=!save.isMuted;persist();updateAllUI();if(save.isMuted)audio.engine(false);else if(state===STATE.FLIGHT)audio.engine(true)};
$('restartBtn').onclick=e=>{e.stopPropagation();resetProgress()};$('restartBtnResults').onclick=e=>{e.stopPropagation();resetProgress()};

function setScreen(which){const menu=$('menu'),res=$('results');if(which==='flight'){menu.classList.add('faded');setTimeout(()=>menu.classList.add('hidden'),220);res.classList.add('hidden','faded');$('hud').classList.add('visible')}else if(which==='menu'){$('hud').classList.remove('visible');res.classList.add('faded');setTimeout(()=>res.classList.add('hidden'),220);menu.classList.remove('hidden');requestAnimationFrame(()=>menu.classList.remove('faded'))}else if(which==='results'){$('hud').classList.remove('visible');menu.classList.add('hidden','faded');res.classList.remove('hidden');requestAnimationFrame(()=>res.classList.remove('faded'))}}

function initFlight(){state=STATE.FLIGHT;resultsReady=false;Object.assign(flight,{alt:0,vel:0,totalStages:save.stages+2,activeStage:save.stages+2,fuel:0,maxFuel:0,perfects:0,chain:0,maxChain:0,sepCredits:0,shake:0,timeScale:1,zoneIndex:0,endedByExplosion:false,cameraLead:0,apogeeTimer:0,apogeeTriggered:false,apogeeHold:false,sepFlash:0,x:0,vx:0,steerTarget:0,steerDir:0,pointerSteer:false,deepSpaceActive:false,deepSpaceAnnounced:false,hazardTimer:.55,impactCooldown:0,impacts:0});flight.particles.length=0;flight.debris.length=0;flight.texts.length=0;flight.shockwaves.length=0;flight.speedLines.length=0;flight.hazards.length=0;generateEnvironment();$('tapHint').textContent='TAP TO SEPARATE • TEAL = PERFECT';$('tapHint').classList.remove('deep-space');$('fuelShell').classList.remove('deep-space');setStageFuel();$('altitude').textContent='0';$('chainChip').classList.remove('show');setScreen('flight');audio.engine(true);toast('LIFTOFF','cyan');haptic(18)}
function setStageFuel(){if(flight.activeStage<=1){flight.fuel=flight.maxFuel=0;audio.engine(false);updateFuel();return}flight.maxFuel=2.15+save.fuel*.24+flight.activeStage*.12;flight.fuel=flight.maxFuel;$('stageChip').textContent='STAGE '+(flight.totalStages-flight.activeStage+1)+' / '+(flight.totalStages-1);updateFuel()}
function updateFuel(){const ratio=flight.maxFuel?clamp(flight.fuel/flight.maxFuel,0,1):0;const el=$('fuelFill');el.style.transform='scaleX('+ratio+')';if(ratio>0&&ratio<.14){el.style.background='linear-gradient(90deg,#28d8be,#85ffe9)';el.style.filter='drop-shadow(0 0 7px #53efd7)'}else if(ratio<.30){el.style.background='linear-gradient(90deg,#d99a26,#ffd268)';el.style.filter='none'}else{el.style.background='linear-gradient(90deg,#e8edf4,#a9b3c4)';el.style.filter='none'}}
