function draw(){const sky=skyColor();ctx.fillStyle=`rgb(${sky.r},${sky.g},${sky.b})`;ctx.fillRect(0,0,W,H);drawAtmosphere(sky);ctx.save();if(flight.shake>0)ctx.translate((Math.random()-.5)*flight.shake,(Math.random()-.5)*flight.shake);
  const spaceA=clamp(sky.space*1.3,0,1),now=performance.now();if(spaceA>.02)for(let i=0;i<flight.stars.length;i++){const s=flight.stars[i],sy=(s.y+flight.alt*.028*s.a)%H,a=spaceA*s.a*(.55+.45*(Math.sin(now*.002+i)*.5+.5));ctx.fillStyle=`rgba(255,255,255,${a})`;ctx.beginPath();ctx.arc(s.x,sy,s.size,0,Math.PI*2);ctx.fill()}
  if(flight.alt<23000){ctx.fillStyle=`rgba(255,255,255,${clamp(1-flight.alt/23000,0,1)*.36})`;for(const c of flight.clouds){const cy=c.y+flight.alt*c.s;if(cy>-80&&cy<H+80){ctx.beginPath();ctx.ellipse(c.x,cy,c.w,c.h,0,0,Math.PI*2);ctx.fill()}}}
  const ry=rocketScreenY(),gy=ry+flight.alt;if(gy<H+180){const grad=ctx.createLinearGradient(0,gy,0,H);grad.addColorStop(0,'#182130');grad.addColorStop(1,'#080b11');ctx.fillStyle=grad;ctx.fillRect(0,gy,W,H-gy+50);ctx.fillStyle='#252f40';ctx.fillRect(W/2-70,gy-5,140,12);ctx.fillStyle='#303b50';ctx.fillRect(W/2+29,gy-145,10,145);ctx.fillRect(W/2+8,gy-110,22,4);ctx.fillRect(W/2+8,gy-62,22,4)}
  ctx.strokeStyle='rgba(255,255,255,.24)';ctx.lineWidth=2;ctx.beginPath();for(const l of flight.speedLines){ctx.moveTo(l.x,l.y);ctx.lineTo(l.x,l.y-l.len)}ctx.stroke();
  for(const d of flight.debris){const sy=ry+(flight.alt-d.worldY);if(sy>-80&&sy<H+80){ctx.save();ctx.translate(W/2+d.x,sy);ctx.rotate(d.rot);ctx.fillStyle='#465067';ctx.fillRect(-14,-15,28,30);ctx.fillStyle='#151c29';ctx.fillRect(-14,4,28,10);ctx.restore()}}
  drawHazards();
  drawRocket(ry);drawApogeeMoment(ry);
  for(const p of flight.particles){ctx.globalAlpha=clamp(p.life,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;
  ctx.lineWidth=3;for(const s of flight.shockwaves){ctx.strokeStyle=`rgba(${s.color},${clamp(s.a,0,1)})`;ctx.beginPath();ctx.arc(rocketScreenX(),ry,s.r,0,Math.PI*2);ctx.stroke()}
  if(flight.sepFlash>0){ctx.globalAlpha=flight.sepFlash*.16;ctx.fillStyle=activeTrail().plasma;ctx.fillRect(0,0,W,H);ctx.globalAlpha=1}
  ctx.textAlign='center';ctx.textBaseline='middle';for(const t of flight.texts){ctx.save();ctx.translate(rocketScreenX(),ry-70-t.y);ctx.scale(t.scale,t.scale);ctx.globalAlpha=clamp(t.life,0,1);ctx.fillStyle=t.color;ctx.shadowColor='#000';ctx.shadowBlur=8;ctx.font='900 40px Arial Narrow, sans-serif';ctx.fillText(t.text,0,0);ctx.restore()}ctx.globalAlpha=1;ctx.restore()}
function loop(ts){if(!lastTime)lastTime=ts;let dt=(ts-lastTime)/1000;lastTime=ts;if(!Number.isFinite(dt)||dt<0)dt=0;dt=Math.min(dt,.1);update(dt);draw();requestAnimationFrame(loop)}

function launch(){if(state!==STATE.MENU)return;ensureAudio();initFlight()}
$('launchBtn').onclick=e=>{e.stopPropagation();launch()};$('continueBtn').onclick=e=>{e.stopPropagation();if(state===STATE.RESULTS&&resultsReady){state=STATE.MENU;setScreen('menu');updateAllUI()}};
addEventListener('pointerdown',e=>{if(e.target.closest&&e.target.closest('button'))return;if(state===STATE.FLIGHT){e.preventDefault();if(flight.deepSpaceActive){flight.pointerSteer=true;flight.steerTarget=clamp(e.clientX-W/2,-W*.38,W*.38)}else separate()}else if(state===STATE.RESULTS&&resultsReady){state=STATE.MENU;setScreen('menu');updateAllUI()}},{passive:false});
addEventListener('pointermove',e=>{if(state===STATE.FLIGHT&&flight.deepSpaceActive&&flight.pointerSteer){e.preventDefault();flight.steerTarget=clamp(e.clientX-W/2,-W*.38,W*.38)}},{passive:false});
addEventListener('pointerup',()=>{flight.pointerSteer=false});addEventListener('pointercancel',()=>{flight.pointerSteer=false});
addEventListener('keydown',e=>{if(e.code==='ArrowLeft'||e.code==='KeyA'){if(state===STATE.FLIGHT&&flight.deepSpaceActive){e.preventDefault();flight.steerDir=-1}}else if(e.code==='ArrowRight'||e.code==='KeyD'){if(state===STATE.FLIGHT&&flight.deepSpaceActive){e.preventDefault();flight.steerDir=1}}else if(e.code==='Space'||e.code==='Enter'){e.preventDefault();if(state===STATE.MENU)launch();else if(state===STATE.FLIGHT&&!flight.deepSpaceActive)separate();else if(state===STATE.RESULTS&&resultsReady){state=STATE.MENU;setScreen('menu');updateAllUI()}}});
addEventListener('keyup',e=>{if((e.code==='ArrowLeft'||e.code==='KeyA')&&flight.steerDir<0)flight.steerDir=0;if((e.code==='ArrowRight'||e.code==='KeyD')&&flight.steerDir>0)flight.steerDir=0});

/* Tiny headless smoke test: open with ?autotest=1 */
async function selfTest(){const out=$('test-status');try{const daily=ensureDailyContracts();if(daily.contracts.length!==3)throw Error('daily-count');for(const c of daily.contracts){c.target=1;c.progress=0;c.claimed=false;if(c.kind==='altitude')c.label='Reach 1 KM in one run';if(c.kind==='perfects')c.label='Land 1 PERFECT separation';if(c.kind==='flights')c.label='Complete 1 flight'}const before=save.credits;launch();await new Promise(r=>setTimeout(r,60));if(state!==STATE.FLIGHT)throw Error('launch');while(flight.activeStage>1){flight.fuel=Math.max(.001,flight.maxFuel*.08);separate();await new Promise(r=>setTimeout(r,15))}flight.alt=(DEEP_SPACE_KM+50)*100;flight.vel=500;flight.hazardTimer=999;update(.016);if(!flight.deepSpaceActive)throw Error('deep-space-active');const x0=flight.x;flight.steerDir=1;updateDeepSpace(.2);flight.steerDir=0;if(flight.x<=x0)throw Error('deep-space-steer');const v0=flight.vel;flight.impactCooldown=0;flight.hazards=[{x:rocketScreenX(),y:rocketScreenY(),r:20,vx:0,vy:0,rot:0,rv:0,seed:1,hit:false}];updateDeepSpace(.016);if(flight.vel>=v0)throw Error('deep-space-impact');flight.hazards.length=0;flight.deepSpaceActive=false;flight.deepSpaceAnnounced=false;flight.x=0;flight.vx=0;flight.alt=12500;flight.vel=-1;update(.016);if(!flight.apogeeTriggered||!flight.apogeeHold)throw Error('apogee-phase');flight.apogeeTimer=.001;update(.02);await new Promise(r=>setTimeout(r,80));if(state!==STATE.RESULTS)throw Error('results');if(save.credits<=before)throw Error('reward');if(!save.dailyContracts.contracts.every(c=>c.claimed))throw Error('daily-claim');if($('payoutDaily').textContent==='+0')throw Error('daily-payout');state=STATE.MENU;save.xp=0;save.bestAlt=0;updateAllUI();const prev=save.selectedLivery;equipCosmetic('livery','void');if(save.selectedLivery!==prev)throw Error('locked-cosmetic');save.xp=16000;updateAllUI();equipCosmetic('livery','void');if(save.selectedLivery!=='void')throw Error('unlock-cosmetic');if(!$('liveryList').innerHTML.includes('VOID'))throw Error('cosmetic-ui');out.textContent='PASS';document.documentElement.dataset.autotest='PASS'}catch(e){out.textContent='FAIL:'+e.message;document.documentElement.dataset.autotest='FAIL'}}

resize();load();requestAnimationFrame(loop);if(new URLSearchParams(location.search).has('autotest'))setTimeout(selfTest,120);
