import Phaser from 'phaser';
import { Flight, grade } from './simulation.js';
import { load,persist,defaults,buy,cost,effect,info,upgradeKeys,maxLevel,tiers,milestones,finishRun,accuracy,type UpgradeKey } from './progression.js';
import { AudioSystem } from './audio.js';
import { World,type WorldBridge } from './world.js';
import './style.css';
const ui=document.querySelector<HTMLDivElement>('#ui')!,toast=document.querySelector<HTMLDivElement>('#toast')!,gradeEl=document.querySelector<HTMLDivElement>('#grade')!;
let save=load(),flight:Flight|null=null,screen='home',countdown=0,accumulator=0,hold=0,hitstop=0,paused=false,result:{rp:number;record:boolean}|null=null,shownMilestones=new Set<number>(),lastPhase='',toastTimer=0,gradeTimer=0,uiClock=0,debug=false;
const audio=new AudioSystem(),world=new World(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const bridge:WorldBridge={flight:null,tier:save.tier,paused:false,shake:save.settings.shake,reduced,tick};world.bridge=bridge;
const game=new Phaser.Game({type:Phaser.AUTO,parent:'world',backgroundColor:'#0a1420',scale:{mode:Phaser.Scale.RESIZE,width:'100%',height:'100%'},render:{antialias:true,pixelArt:false},fps:{target:60,smoothStep:true},scene:[world],audio:{noAudio:true}});
const km=(n:number)=> (n/1000).toLocaleString('en-US',{minimumFractionDigits:1,maximumFractionDigits:1});
const num=(n:number)=>Math.round(n).toLocaleString('en-US');
const button=(action:string,label:string,cls='')=>`<button type="button" data-action="${action}" class="${cls}">${label}</button>`;
const top=(label:string)=>`<header class="panel-head"><span>APOGEE / ${label}</span>${button('home','×','icon')}</header>`;
function saveNow(){document.querySelector<HTMLElement>('#save-warning')!.hidden=persist(save);}
function settingsSync(){audio.sfx=save.settings.sfx;audio.music=save.settings.music;bridge.shake=save.settings.shake;bridge.tier=save.tier;}
function notify(text:string){toast.textContent=text;toast.classList.add('show');toastTimer=3;}
function home(){screen='home';flight=null;bridge.flight=null;paused=false;bridge.paused=false;world.reset?.();render();}
function render(){
 ui.className=screen==='flight'?'flight-ui':'menu-ui';
 document.querySelector('#game')!.classList.toggle('playing',screen==='flight');
 if(screen==='home')ui.innerHTML=`<div class="home-top"><a class="back" href="../../index.html">← FORGE ARCADE</a><span class="edition">FLIGHT PROGRAM / 001</span><div class="title-lockup"><span class="eyebrow">A ONE-BUTTON SPACE ODYSSEY</span><h1>APOGEE<span>•</span></h1><p>HOW FAR CAN YOU GO?</p></div><div class="best"><span>BEST APOGEE</span><strong>${km(save.best)} <small>KM</small></strong></div></div><div class="home-bottom"><div class="rocket-label"><span>0${save.tier+1} / ${tiers[save.tier].name}</span><span>${3+save.upgrades.staging} STAGES</span></div>${button('launch','LAUNCH <span>↗</span>','primary launch')}<div class="menu-grid">${button('hangar','HANGAR')}${button('upgrades','UPGRADES')}${button('records','RECORDS')}${button('settings','SETTINGS')}</div><p class="hint">WAIT FOR THE LAST SLIVER. THEN SEPARATE.</p><span class="controls">CLICK / TAP / SPACE</span></div>`;
 if(screen==='flight')ui.innerHTML=`<header class="flight-head"><span class="mission">FLIGHT ${String(save.launches).padStart(3,'0')}</span>${button('pause','Ⅱ','icon pause')}<span class="eyebrow">CURRENT ALTITUDE</span><div class="altitude"><b id="altitude">0.0</b><small> KM</small></div><div class="telemetry"><span id="velocity">0 m/s</span><i></i><span id="zone">TROPOSPHERE</span></div></header><aside class="journey">${[384400,400,100,50,10].map(n=>`<span style="bottom:${Math.log10(1+n)/Math.log10(384401)*96}%">${n===384400?'MOON':n}</span>`).join('')}<i id="journey-dot"></i><small>KM</small></aside><div id="countdown" class="countdown"></div><section class="stage-hud"><div class="stage-line"><span id="stage-label">STAGE 01 / 03</span><span id="phase-label">IGNITION SEQUENCE</span></div><div id="fuel-track" class="fuel-track"><div id="fuel"></div><div class="window good"></div><div class="window great"></div><div class="window perfect"></div></div><div class="fuel-labels"><span>↑ PERFECT WINDOW</span><span id="fuel-label">FUEL 100%</span></div><p id="instruction">Watch the fuel. Separate just before empty.</p>${button('stage','SEPARATE <span>SPACE / TAP</span>','stage-button')}</section><div id="pause-layer" hidden><span class="eyebrow">FLIGHT ON HOLD</span><h2>PAUSED</h2>${button('resume','RESUME FLIGHT','primary')}${button('abort','END FLIGHT')}</div><pre id="debug" hidden></pre>`;
 if(screen==='results'&&flight&&result)ui.innerHTML=`<div class="results panel">${top('FLIGHT REPORT')}<span class="result-kicker ${result.record?'record':''}">${flight.phase==='failed'?'MISSION FAILED':result.record?'NEW ALTITUDE RECORD':'FLIGHT COMPLETE'}</span><h2>${flight.phase==='failed'?'SIGNAL LOST':'APOGEE'}</h2><div class="result-alt">${km(flight.altitude)}<small> KM</small></div><p class="result-sub">${flight.phase==='failed'?'Stage pressure exceeded. Next time, let go sooner.':'For a moment, everything stood still.'}</p><div class="report-row"><span>BEST APOGEE</span><strong>${km(save.best)} KM</strong></div><div class="report-row"><span>STAGING ACCURACY</span><strong>${accuracy(flight)}%</strong></div><div class="grades">${(['PERFECT','GREAT','GOOD','EARLY','CRITICAL'] as const).map(k=>`<div><b>${flight!.grades[k]}</b><span>${k}</span></div>`).join('')}</div><div class="reward"><span>RESEARCH EARNED</span><strong>+${num(result.rp)} <small>RP</small></strong></div>${button('launch','LAUNCH AGAIN ↗','primary')}<div class="two-buttons">${button('upgrades','UPGRADES')}${button('home','HOME')}</div></div>`;
 if(screen==='upgrades')ui.innerHTML=`<div class="panel scroll-panel">${top('RESEARCH')}<span class="eyebrow">MAKE THE NEXT FLIGHT COUNT</span><h2>UPGRADES</h2><p class="balance">${num(save.rp)} <small>RP AVAILABLE</small></p><div class="upgrade-list">${upgradeKeys.map(k=>{const n=save.upgrades[k],max=n>=maxLevel(k),price=cost(k,n);return `<article class="upgrade"><div><h3>${info[k].name}</h3><span class="level">LEVEL ${String(n).padStart(2,'0')}</span></div><p>${info[k].description} <b>${effect(k,n)}</b> <span>→ ${max?'MAX':effect(k,n+1)}</span></p><div class="upgrade-bottom"><div class="level-track"><i style="width:${n/maxLevel(k)*100}%"></i></div><button type="button" data-buy="${k}" ${max||save.rp<price?'disabled':''}>${max?'MAX LEVEL':`${num(price)} RP +`}</button></div></article>`;}).join('')}</div>${button('launch','LAUNCH ↗','primary')}</div>`;
 if(screen==='hangar')ui.innerHTML=`<div class="panel scroll-panel">${top('HANGAR')}<span class="eyebrow">BUILT FOR THE LONG CLIMB</span><h2>THE FLEET</h2><p class="panel-copy">Your rocket evolves with altitude records and engine research. All unlocked technology flies with you.</p><div class="tier-list">${tiers.map((t,i)=>`<article class="tier ${i<=save.tier?'unlocked':''}"><span class="tier-rocket" style="--tier-width:${14+i*3}px">▲<i></i>♨</span><div><small>TIER 0${i+1} ${i===save.tier?' / ACTIVE':i<save.tier?' / UNLOCKED':' / LOCKED'}</small><h3>${t.name}</h3><p>${t.km?`${num(t.km)} KM + ENGINE ${t.level}`:'YOUR FIRST STEP INTO THE SKY'}</p></div></article>`).join('')}</div>${button('launch','FLY '+tiers[save.tier].name+' ↗','primary')}</div>`;
 if(screen==='records')ui.innerHTML=`<div class="panel scroll-panel">${top('FLIGHT ARCHIVE')}<h2>RECORDS</h2><div class="archive-best">${km(save.best)} <small>KM</small></div><div class="report-row"><span>TOTAL LAUNCHES</span><strong>${num(save.launches)}</strong></div><div class="report-row"><span>PERFECT SEPARATIONS</span><strong>${num(save.perfects)}</strong></div><div class="report-row"><span>PEAK VELOCITY</span><strong>${num(save.highestVelocity)} m/s</strong></div><h3 class="milestones-title">DISTANCE MARKERS</h3>${milestones.map(m=>`<div class="milestone ${save.achievements.includes(m.km)?'reached':''}"><span>${save.achievements.includes(m.km)?'◆':'◇'} ${m.name}</span><b>${num(m.km)} KM</b></div>`).join('')}</div>`;
 if(screen==='settings')ui.innerHTML=`<div class="panel">${top('SETTINGS')}<h2>FLIGHT DECK</h2><p class="panel-copy">A quieter climb, if you prefer.</p>${(['music','sfx','shake'] as const).map(k=>`<div class="setting"><label for="setting-${k}">${{music:'MUSIC / AMBIENCE',sfx:'SOUND EFFECTS',shake:'SCREEN SHAKE'}[k]}</label><button id="setting-${k}" role="switch" aria-checked="${save.settings[k]}" data-setting="${k}">${save.settings[k]?'ON':'OFF'}</button></div>`).join('')}<p class="panel-copy">${reduced?'Reduced motion is active. Camera shake is suppressed.':'Space, click, or tap separates a stage. Escape pauses a flight.'}<br><br>Progress saves automatically on this browser.</p><div class="reset-area">${button('reset','RESET PROGRESS','danger')}<div id="reset-confirm" hidden><p>This permanently clears this game’s research and records.</p>${button('confirm-reset','YES, RESET APOGEE','danger')}${button('cancel-reset','CANCEL')}</div></div></div>`;
 requestAnimationFrame(()=>{if(screen!=='flight')ui.querySelector<HTMLButtonElement>('button')?.focus({preventScroll:true});});
}
function launch(){audio.unlock();settingsSync();flight=new Flight({...save.upgrades});bridge.flight=flight;world.reset();screen='flight';countdown=3.1;accumulator=0;hold=0;hitstop=0;paused=false;bridge.paused=false;result=null;lastPhase='ready';shownMilestones=new Set();save.launches++;saveNow();render();audio.tone('launch');}
function separate(){if(screen!=='flight'||paused||countdown>0||!flight)return;const e=flight.separate();if(!e)return;world.separate(e);audio.tone(e.grade==='PERFECT'?'perfect':'separate');gradeEl.textContent=e.grade;gradeEl.className='show '+e.grade.toLowerCase();gradeTimer=1; if(e.grade==='PERFECT')hitstop=.045;}
function setPause(value:boolean){if(screen!=='flight')return;paused=value;bridge.paused=value;document.querySelector<HTMLElement>('#pause-layer')!.hidden=!value;audio.update(false,0,value);if(value)ui.querySelector<HTMLButtonElement>('[data-action="resume"]')?.focus();else ui.querySelector<HTMLButtonElement>('[data-action="stage"]')?.focus();}
function tick(dt:number){
 if(toastTimer>0&&(toastTimer-=dt)<=0)toast.classList.remove('show');if(gradeTimer>0&&(gradeTimer-=dt)<=0)gradeEl.className='';
 settingsSync();audio.update(flight?.phase==='burn'&&countdown<=0,flight?.altitude??0,paused);
 if(screen!=='flight'||!flight||paused)return;
 if(countdown>0){countdown-=dt;const el=document.querySelector<HTMLElement>('#countdown')!;el.textContent=countdown>.5?String(Math.ceil(countdown-.5)):'IGNITION';if(countdown<=0){el.textContent='';flight.start();if(save.settings.shake&&!reduced)world.cameras.main.shake(180,.002);}return;}
 if(hitstop>0){hitstop-=dt;return;}
 accumulator+=dt;while(accumulator>=1/120){flight.step(1/120);accumulator-=1/120;}
 if(flight.phase!==lastPhase){lastPhase=flight.phase;if(flight.phase==='coast')notify('ENGINE CUTOFF / COASTING TO APOGEE');if(flight.phase==='failed'){world.explode();audio.tone('explode');hold=1.15;}if(flight.phase==='apogee'){world.celebrate();audio.tone('achievement');hold=1.25;}}
 if(['apogee','failed'].includes(flight.phase)){hold-=dt;if(hold<=0){result=finishRun(save,flight);saveNow();screen='results';render();return;}}
 for(const m of milestones)if(flight.altitude>=m.km*1000&&!shownMilestones.has(m.km)){shownMilestones.add(m.km);notify(`${num(m.km)} KM / ${m.name}`);audio.tone('achievement');}
 uiClock+=dt;if(uiClock<.05)return;uiClock=0;
 document.querySelector('#altitude')!.textContent=km(flight.altitude);document.querySelector('#velocity')!.textContent=`${num(flight.velocity)} m/s`;
 const a=flight.altitude/1000;document.querySelector('#zone')!.textContent=a<12?'TROPOSPHERE':a<50?'STRATOSPHERE':a<85?'MESOSPHERE':a<100?'EDGE OF SPACE':a<400?'SPACE':'BEYOND THE BLUE';
 document.querySelector('#stage-label')!.textContent=`STAGE ${String(flight.stage+1).padStart(2,'0')} / ${String(flight.stages.length).padStart(2,'0')}`;
 const final=flight.stage===flight.stages.length-1;
 document.querySelector('#phase-label')!.textContent=flight.phase==='burn'?(final?'FINAL BURN / AUTO CUTOFF':grade(flight.fuelFraction,save.upgrades.guidance)):flight.phase.toUpperCase();
 document.querySelector<HTMLElement>('#fuel')!.style.transform=`scaleX(${Math.max(0,flight.fuelFraction)})`;
 document.querySelector<HTMLElement>('#fuel-track')!.className='fuel-track '+(flight.fuelFraction<.03?'critical':flight.fuelFraction<.1?'ideal':'');
 document.querySelector<HTMLElement>('.window.perfect')!.style.width=`${3+save.upgrades.guidance*.15}%`;
 document.querySelector('#fuel-label')!.textContent=`FUEL ${Math.max(0,Math.ceil(flight.fuelFraction*100))}%`;
 document.querySelector('#instruction')!.textContent=flight.phase==='coast'?'Engines quiet. Let momentum carry you.':final?'Final stage burns automatically. Enjoy the climb.':'Wait for the last sliver. Then separate.';
 const stageButton=ui.querySelector<HTMLButtonElement>('[data-action="stage"]')!;stageButton.disabled=final||flight.phase!=='burn';stageButton.innerHTML=final?'AUTOMATIC CUTOFF':'SEPARATE <span>SPACE / TAP</span>';
 document.querySelector<HTMLElement>('#journey-dot')!.style.bottom=`${Math.min(96,Math.log10(1+a)/Math.log10(384401)*100)}%`;
 if(debug){const el=document.querySelector<HTMLElement>('#debug')!;el.hidden=false;el.textContent=`ALT ${flight.altitude.toFixed(0)} m\nVEL ${flight.velocity.toFixed(1)} m/s\nACC ${flight.acceleration.toFixed(2)}\nMASS ${flight.mass.toFixed(1)} kg\nFUEL ${flight.fuelFraction.toFixed(3)}\nSTAGE ${flight.stage+1}\nG ${flight.gravity.toFixed(3)}\nDRAG ${flight.drag.toFixed(1)}\nFPS ${game.loop.actualFps.toFixed(1)}\nR RP · U upgrades · T tier · A altitude`;}
}
ui.addEventListener('click',event=>{
 const target=(event.target as HTMLElement).closest<HTMLButtonElement>('button');if(!target)return;audio.unlock();audio.tone('ui');
 if(target.dataset.buy){if(buy(save,target.dataset.buy as UpgradeKey)){saveNow();settingsSync();render();}return;}
 if(target.dataset.setting){const key=target.dataset.setting as keyof typeof save.settings;save.settings[key]=!save.settings[key];settingsSync();saveNow();render();return;}
 switch(target.dataset.action){case'launch':launch();break;case'home':home();break;case'stage':separate();break;case'pause':setPause(true);break;case'resume':setPause(false);break;case'abort':if(flight){flight.phase='failed';result=finishRun(save,flight);saveNow();paused=false;bridge.paused=false;screen='results';render();}break;case'reset':document.querySelector<HTMLElement>('#reset-confirm')!.hidden=false;break;case'cancel-reset':document.querySelector<HTMLElement>('#reset-confirm')!.hidden=true;break;case'confirm-reset':save=defaults();saveNow();home();notify('FLIGHT ARCHIVE RESET');break;default:if(target.dataset.action){screen=target.dataset.action;render();}}
});
document.querySelector('#game')!.addEventListener('pointerdown',event=>{if((event as PointerEvent).button===0&&!(event.target as HTMLElement).closest('button,a,input')){audio.unlock();separate();}});
window.addEventListener('keydown',event=>{
 if(event.code==='Escape'&&screen==='flight'){event.preventDefault();setPause(!paused);return;}
 if(event.code==='Space'&&screen==='flight'){const target=event.target as HTMLElement;if(target.closest('button,a,input,select,textarea')&&!target.closest('[data-action=stage]'))return;event.preventDefault();if(!event.repeat)separate();return;}
 if(import.meta.env.DEV){if(event.code==='Backquote'){debug=!debug;const el=document.querySelector<HTMLElement>('#debug');if(el)el.hidden=!debug;}if(debug){if(event.code==='KeyR'){save.rp+=10000;saveNow();notify('+10,000 DEV RP');}if(event.code==='KeyU'){upgradeKeys.forEach(k=>save.upgrades[k]=Math.min(maxLevel(k),save.upgrades[k]+1));saveNow();notify('DEV UPGRADE +1');}if(event.code==='KeyT'){save.tier=(save.tier+1)%6;notify('DEV TIER '+tiers[save.tier].name);}if(event.code==='KeyA'&&flight){flight.altitude=flight.altitude<100000?100000:flight.altitude*10;notify('DEV ALTITUDE');}}}
});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&screen==='flight')setPause(true);audio.update(false,0,document.hidden);});
settingsSync();render();
